name: build-test-push

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/ci-demo

jobs:
  build_test_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      # тесты (простейшие)
      - name: Run tests
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          pip install -r requirements.txt pytest
          pytest -q

      # логин в GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # сборка и пуш образа
      - name: Build image
        run: docker build -t $IMAGE_NAME:${{ github.sha }} -t $IMAGE_NAME:latest .

      - name: Push image
        run: |
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest
